name: MrDarkPrince

on:
  push:
  pull_request:

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black

      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive --aggressive --ignore=W605 ./*.py

      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .

      - name: Lint with isort and black
        run: |
          isort .
          black .

      - name: Commit changes
        run: |
          git config --global user.name "Mr-Dark-Prince"
          git config --global user.email "73339924+Mr-Dark-Prince@users.noreply.github.com"
          git add .
          git commit -m "Apply PEP8 formatting" --no-verify

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: ${{ github.ref }}
